---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adangime/public_html/
    - /bin/rsync -av index.php $DEPLOYPATH
    - /bin/rsync -av description.php $DEPLOYPATH
    - /bin/rsync -av sendEmail.php $DEPLOYPATH